title: &title "Settings"
type: utility
changelogURL:
items:
  - date: 2024-10-04
    page: *title
    summary: Added new `$theme-utility-breakpoints-custom` setting.
    summaryAdditional: Users can now set custom breakpoints which will generate utilities alongside the default system breakpoints.
    affectsSettings: true
    affectsStyles: true
    githubPr: 6048
    githubRepo: uswds
    versionUswds: 3.9.0
  - date: 2024-03-11
    page: *title
    summary: Added new sidenav setting to temporarily address visual regression in new markup guidance.
    summaryAdditional: The new setting `$theme-sidenav-reorder` allows users to temporarily reorder the sidenav with CSS. Users should follow new markup recommendation in code example to avoid accessibility issues.
    isBreaking: false
    affectsAccessibility: true
    affectsContent:
    affectsSettings: true
    affectsStyles: true
    githubPr: 5809
    githubRepo: uswds
    versionUswds: 3.8.0
  - date: 2024-03-11
    page: *title
    summary: Added `$theme-table-background-color` and `$theme-table-sticky-top-offset` settings.
    affectsStyles: true
    affectsSettings: true
    githubPr: 5420
    githubRepo: uswds
    versionUswds: 3.8.0
  - date: 2024-03-11
    page: *title
    summary: Added color contrast checks for disabled tokens.
    summaryAdditional: On compilation, USWDS will test disabled element color contrast and provide a fallback color if minimum contrast is not met. If the fallback does not meet minimum requirements, USWDS will provide a warning in the terminal.
    affectsAccessibility: true
    affectsStyles: true
    githubPr: 5455
    githubRepo: uswds
    versionUswds: 3.8.0
  - date: 2024-03-11
    page: *title
    summary: Added button icon gap setting.
    summaryAdditional: You can now customize the size of the gap between a button's text and icon with `$theme-button-icon-gap`.
    affectsStyles: true
    affectsSettings: true
    githubPr: 5398
    githubRepo: uswds
    versionUswds: 3.8.0
  - date: 2023-12-08
    page: *title
    summary: Fixed a bug that prevented `$theme-max-header-width` from accepting a value of "none".
    affectsStyles: true
    githubPr: 5624
    githubRepo: uswds
    versionUswds: 3.7.1
  - date: 2023-11-09
    page: *title
    summary: Fixed a bug that prevented `$theme-site-margins-width` from accepting expected token values.
    affectsSettings: true
    affectsStyles: true
    githubPr: 5582
    githubRepo: uswds
    versionUswds: 3.7.0
  - date: 2023-11-09
    page: *title
    summary: Fixed a bug that prevented `$theme-card-padding-y` from accepting expected token values.
    affectsSettings: true
    affectsStyles: true
    githubPr: 5571
    githubRepo: uswds
    versionUswds: 3.7.0
  - date: 2023-08-23
    page: *title
    summary: Updated default disabled color settings values and added `$theme-color-disabled-lighter` and `$theme-color-disabled-darker`.
    summaryAdditional: If your project customizes disabled color settings, you probably need to update your configuration.
    isBreaking: true
    affectsSettings: true
    affectsStyles: true
    githubPr: 5402
    githubRepo: uswds
    versionUswds: 3.6.0
  - date: 2023-08-23
    page: *title
    summary: Fixed configuration errors with disabled color settings.
    summaryAdditional: All disabled color settings should now be configurable and accept hex color values.
    affectsSettings: true
    affectsStyles: true
    githubPr: 5402
    githubRepo: uswds
    versionUswds: 3.6.0
  - date: 2023-08-23
    page: *title
    summary: Fixed a bug that prevented `$theme-body-font-size` from accepting `2xs` and `3xs` size tokens.
    affectsStyles: true
    githubPr: 5363
    githubRepo: uswds
    versionUswds: 3.6.0
  - date: 2023-07-28
    page: *title
    summary: Added a note about configuring settings that are described using dot notation.
    affectsGuidance: true
    githubPr: 2122
    githubRepo: uswds-site
  - date: 2023-06-09
    page: *title
    summary: Added accordion color settings.
    summaryAdditional: You can now customize accordion button and content background colors with `$theme-accordion-button-background-color` and `$theme-accordion-background-color`.
    affectsGuidance: true
    affectsSettings: true
    affectsStyles: false
    githubPr: 2081
    githubRepo: uswds-site
    versionUswds: 3.5.0
  - date: 2023-06-09
    page: *title
    summary: Added settings for announcing external links.
    summaryAdditional: Added `$theme-external-link-sr-label-tab-same` and `$theme-external-link-sr-label-tab-new` to control how screen readers announce external links.
    affectsSettings: true
    affectsAccessibility: true
    githubPr: 5166
    githubRepo: uswds
    versionUswds: 3.5.0
  - date: 2023-06-09
    page: *title
    summary: Updated individual Sass map settings without affecting defaults.
    summaryAdditional: Now adjusting a single Sass map setting no longer sets all other values in the map to `false`. Users can now update only the map values they wish to change.
    isBreaking: true
    affectsGuidance: true
    affectsStyles: true
    githubPr: 5216
    githubRepo: uswds
    versionUswds: 3.5.0
  - date: 2023-03-20
    page: *title
    summary: Updated settings information to match what is found in USWDS.
    affectsGuidance: true
    githubPr: 2016
    githubRepo: uswds-site
  - date: 2023-03-09
    page: *title
    summary: Added `$theme-font-browser-compatibility` setting.
    summaryAdditional: We now only output `woff2` fonts in our `@font-face` rules. If you need `woff` and `ttf` for IE11 compatibility, set this new setting to `true`.
    affectsSettings: true
    affectsGuidance: true
    githubPr: 5108
    githubRepo: uswds
    versionUswds: 3.4.0
  - date: 2023-03-09
    page: *title
    summary: Removed `woff` and `ttf` file format requirements from custom font source settings.
    affectsAssets: true
    affectsGuidance: true
    githubPr: 5108
    githubRepo: uswds
    versionUswds: 3.4.0
  - date: 2022-09-16
    page: *title
    summary: Fixed typos in `primary-vivid` and `secondary-vivid` variable names.
    affectsGuidance: true
    githubPr: 1767
    githubRepo: uswds-site
  - date: 2022-09-26
    page: *title
    summary: Clarified instructions for settings configuration.
    affectsGuidance: true
    githubPr: 1755
    githubRepo: uswds-site
  - date: 2022-08-29
    page: *title
    summary: Added documentation for `$theme-footer-max-width`.
    affectsGuidance: true
    githubPr: 1719
    githubRepo: uswds-site
  - date: 2022-08-05
    page: *title
    summary: Updated the value of `$theme-hero-image`.
    summaryAdditional: We replaced our default hero image (PNG) with an optimized image (JPG).
    isBreaking: true
    affectsAssets: true
    affectsStyles: true
    githubPr: 4885
    githubRepo: uswds
    versionUswds: 3.1.0
  - date: 2022-07-17
    page: *title
    summary: Added note about error handling for `@use "uswds-core" with ()`.
    affectsGuidance: true
    githubPr: 1698
    githubRepo: uswds-site
  - date: 2022-06-17
    page: *title
    summary: Updated value of `$theme-table-border-color` from `default` to `ink`.
    affectsStyles: true
    githubPr: 4712
    githubRepo: uswds
    versionUswds: 3.0.2
  - date: 2022-06-17
    page: *title
    summary: Fixed errors related to `$theme-body-background-color`.
    summaryAdditional: Updated icons so that custom background colors no longer cause compile failures.
    affectsAssets: true
    affectsStyles: true
    githubPr: 4686
    githubRepo: uswds
    versionUswds: 3.0.2
  - date: 2022-06-17
    page: *title
    summary: Fixed precedence issue related to `$theme-global-content-styles` and `$theme-global-paragraph-styles`.
    affectsStyles: true
    githubPr: 4726
    githubRepo: uswds
    versionUswds: 3.0.2
  - date: 2022-04-28
    page: *title
    summary: |
      Replaced the outdated text: `$output-all-utilities` with updated: `$output-these-utilities`.
    summaryAdditional: This setting allows users to create a list of the utility modules they want to include in the project.
    affectsStyles: true
    githubPr: 4631
    githubRepo: uswds
    versionUswds: 3.0.0
  - date: 2022-04-28
    page: *title
    summary: Updated the settings page to use USWDS 3.0 conventions.
    affectsGuidance: true
    githubPr: 1538
    githubRepo: uswds-site
  - date: 2022-03-11
    page: *title
    summary: Updated value of `$theme-modal-lg-max-width` from `800px` to `880px`.
    affectsGuidance: true
    githubPr: 1474
    githubRepo: uswds-site
  - date: 2021-06-16
    page: *title
    summary: Updated input settings.
    summaryAdditional: Added `$theme-input-background-color`; removed `$theme-input-tile-background-color-selected`, `$theme-input-tile-border-color`, and `$theme-input-tile-border-color-selected`.
    affectsStyles: true
    githubPr: 4199
    githubRepo: uswds
    versionUswds: 2.12.0
  - date: 2021-06-16
    page: *title
    summary: Added pagination settings.
    affectsStyles: true
    githubPr: 4175
    githubRepo: uswds
    versionUswds: 2.12.0
  - date: 2021-06-16
    page: *title
    summary: Updated values for `$theme-color-success-dark` and `$theme-color-success-darker`.
    affectsStyles: true
    githubPr: 4183
    githubRepo: uswds
    versionUswds: 2.12.0
  - date: 2021-04-28
    page: *title
    summary: Updated our docs and settings to remove `$theme-site-max-width`.
    summaryAdditional: In its place, use `$theme-grid-container-max-width`.
    affectsGuidance: true
    githubPr: 1198
    githubRepo: uswds-site
    versionUswds:
  - date: 2021-03-17
    page: *title
    summary: Added `$theme-prefix-separator`.
    summaryAdditional: This setting allows you to output any character or string for the separator between the prefix and main class.
    affectsStyles: true
    githubPr: 4085
    githubRepo: uswds
    versionUswds: 2.11.0
  - date: 2021-03-17
    page: *title
    summary: Added `$theme-alert-padding-y`.
    affectsStyles: true
    githubPr: 4079
    githubRepo: uswds
    versionUswds: 2.11.0
  - date: 2021-03-17
    page: *title
    summary: Added sortable table settings and updated values of other table settings.
    affectsStyles: true
    githubPr: 3950
    githubRepo: uswds
    versionUswds: 2.11.0
  - date: 2021-03-17
    page: *title
    summary: Added modal settings.
    affectsStyles: true
    githubPr: 3981
    githubRepo: uswds
    versionUswds: 2.11.0
  - date: 2021-03-17
    page: *title
    summary: Added icon list settings.
    affectsStyles: true
    githubPr: 3876
    githubRepo: uswds
    versionUswds: 2.11.0
  - date: 2021-03-03
    page: *title
    summary: Improved use of `$theme-text-` and `$theme-link-` settings in components and variants like `usa-dark-background` and `usa-section--dark`.
    affectsStyles: true
    githubPr: 4059
    githubRepo: uswds
    versionUswds: 2.10.2
  - date: 2021-02-19
    page: *title
    summary: Added new settings and updated settings values to repair color contrast issues.
    summaryAdditional: Added `$theme-body-background-color`, `$theme identifier-primary-link-color`, `$theme-text-` settings, and `$theme-alert-` settings; changed the value of `$theme-breadcrumb-background-color`.
    affectsStyles: true
    githubPr: 3966
    githubRepo: uswds
    versionUswds: 2.10.1
  - date: 2021-02-19
    page: *title
    summary: Replaced hard-coded value for alert component icon size with `$theme-alert-icon-size`.
    summaryAdditional: This update also changes the default value of the `$theme-alert-icon-size` from `4` to `5`.
    isBreaking: true
    affectsStyles: true
    githubPr: 3942
    githubRepo: uswds
    versionUswds: 2.10.1
  - date: 2020-12-17
    page: *title
    summary: Added support for custom bold font weight by defining theme bold styles with `$theme-font-weight-bold`.
    affectsStyles: true
    githubPr: 3811
    githubRepo: uswds
    versionUswds: 2.10.0
