version: 2.1

orbs:
  snyk: snyk/snyk@1.1.2

jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.4-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
      - restore_cache:
          keys:
            - gem-cache-{{ checksum "Gemfile.lock" }}
            - gem-cache
      - run:
          name: Install ruby dependencies
          command: |
            gem update --system
            gem install bundler
            bundle config set --local path 'vendor/bundle'
            bundle install --jobs=4 --retry=3
      - run:
          name: Install scss_lint
          command: gem install scss_lint
      - save_cache:
          key: gem-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Install node dependencies
          command: npm install
      - run:
          name: Build USWDS if needed
          command: npm run build-uswds
      - save_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - snyk/scan:
          organization: uswds
      - run:
          name: Run test
          command: npm run test:ci

workflows:
  version: 2
  circle-uswds-site:
    jobs:
      - build
